# Generated by Django 2.0.1 on 2018-01-29 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sound_store', '0002_auto_20180116_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=4096)),
                ('name', models.CharField(max_length=128)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sound_store.Users')),
            ],
        ),
    ]
