# Generated by Django 2.0.1 on 2018-02-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sound_store', '0005_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='sounds',
            old_name='user_id',
            new_name='user',
        ),
    ]
