# Generated by Django 2.0.1 on 2018-02-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sound_store', '0006_auto_20180206_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=4096)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='path',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='stream',
        ),
        migrations.AddField(
            model_name='streams',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sound_store.Projects'),
        ),
    ]
